name: Ansible Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd ansible
          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"
          ANSIBLE_VERSION=$(grep -oP "^ARG ANSIBLE_VERSION=\K.*" Dockerfile)
          echo "ANSIBLE_VERSION=${ANSIBLE_VERSION}" >> $GITHUB_ENV
          echo "ANSIBLE_VERSION=${ANSIBLE_VERSION}"

      - name: Build and push Docker image
        run: |
          cd ansible
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}/ansible:${{ env.ANSIBLE_VERSION }}-alpine${{ env.ALPINE_VERSION }} \
            --tag ghcr.io/${{ github.repository }}/ansible:${{ env.ANSIBLE_VERSION }} \
            --tag ghcr.io/${{ github.repository }}/ansible:alpine${{ env.ALPINE_VERSION }} \
            --tag ghcr.io/${{ github.repository }}/ansible:latest \
            --push \
            .
