name: Env-Lint Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'env-lint/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd env-lint
          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"
          DOTENV_LINTER_VERSION=$(grep -oP "^ARG DOTENV_LINTER_VERSION=\K.*" Dockerfile)
          echo "DOTENV_LINTER_VERSION=${DOTENV_LINTER_VERSION}" >> $GITHUB_ENV
          echo "DOTENV_LINTER_VERSION=${DOTENV_LINTER_VERSION}"

      - name: Build and push Docker image
        run: |
          cd env-lint
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}/env-lint:${{ env.DOTENV_LINTER_VERSION }}-alpine${{ env.ALPINE_VERSION }} \
            --tag ghcr.io/${{ github.repository }}/env-lint:${{ env.DOTENV_LINTER_VERSION }} \
            --tag ghcr.io/${{ github.repository }}/env-lint:alpine${{ env.ALPINE_VERSION }} \
            --tag ghcr.io/${{ github.repository }}/env-lint:latest \
            --push \
            .
