name: Docker Build- packer

on:
  push:
    branches:
      - main
    paths:
      - 'packer/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd packer
          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"
          PACKER_VERSION=$(grep -oP "^ARG PACKER_VERSION=\K.*" Dockerfile)
          echo "PACKER_VERSION=${PACKER_VERSION}" >> $GITHUB_ENV
          echo "PACKER_VERSION=${PACKER_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: packer
          file: packer/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/packer:${{ env.PACKER_VERSION }}-alpine${{ env.ALPINE_VERSION }}
            ghcr.io/${{ github.repository }}/packer:${{ env.PACKER_VERSION }}
            ghcr.io/${{ github.repository }}/packer:alpine${{ env.ALPINE_VERSION }}
            ghcr.io/${{ github.repository }}/packer:latest

      - name: Run Slack Notification
        if: always()
        uses: sudo88com/slacknotify-action@v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
